version: '2'
services:
  botium:
    build:
      context: >-
        /home/akhil/Downloads/botium/botiumwork/core-CreateNewConversation-20180716-145502-yasxB/git/Node/core-CreateNewConversation
    logging:
      driver: syslog
      options:
        syslog-address: 'udp://127.0.0.1:47100'
    volumes:
      - >-
        /home/akhil/Downloads/botium/botiumwork/core-CreateNewConversation-20180716-145502-yasxB/git/Node/core-CreateNewConversation:/usr/src/app
    environment:
      IS_BOTIUM_CONTAINER: 'true'
      MICROSOFT_APP_ID: my microsoft app id
      MICROSOFT_APP_PASSWORD: my microsoft app password
      NODE_DEBUG: botbuilder
      DEBUG: '*'
  botium-botframeworkmock:
    build:
      context: >-
        /home/akhil/Downloads/botium/botiumwork/core-CreateNewConversation-20180716-145502-yasxB/botframeworkmock
    logging:
      driver: syslog
      options:
        syslog-address: 'udp://127.0.0.1:47100'
    volumes:
      - >-
        /home/akhil/Downloads/botium/botiumwork/core-CreateNewConversation-20180716-145502-yasxB/botframeworkmock:/usr/src/app
    ports:
      - '46500:46500'
    environment:
      BOTIUM_BOTFRAMEWORK_WEBHOOKPORT: 3978
      BOTIUM_BOTFRAMEWORK_WEBHOOKPATH: api/messages
      BOTIUM_BOTFRAMEWORK_APP_ID: my microsoft app id
      BOTIUM_BOTFRAMEWORK_CHANNEL_ID: facebook
      BOTIUM_BOTFRAMEWORK_PUBLISHPORT: 46500
